--INSERT INTO STATIC VALUES STATUS TABLE
INSERT INTO STATUS VALUES(1,'Cancelled');
INSERT INTO STATUS VALUES(2,'Partialship');
INSERT INTO STATUS VALUES(3,'Processed');
INSERT INTO STATUS VALUES(4,'Reconciled');
INSERT INTO STATUS VALUES(5,'Tied');
INSERT INTO STATUS VALUES(6,'Shipped');

--INSERT INTO STATIC VALUES SITE TABLE
INSERT INTO SITE VALUES(1,'wildcat.ca');
INSERT INTO SITE VALUES(2,'wildcat.com');


--CREATE SEQUENCE FOR VENDOR TABLE
CREATE SEQUENCE VENDORID_SEQ
MINVALUE 1
INCREMENT BY 1;

--INSERT IN VENDOR TABLE
INSERT INTO VENDOR(VENDORID,VENDORNAME)
SELECT VENDORID_SEQ.NEXTVAL,VENDORNAME
FROM (
SELECT DISTINCT VENDORNAME FROM VENDOR_TEMP);

--INSERT IN CUSTOMER TABLE
INSERT INTO CUSTOMER(customerid,firstname,lastname,email,username,password,accountcreationdate,phoneno)
SELECT DISTINCT customerid,firstname,lastname,email,username,password,accountcreationdate,phoneno
FROM CUSTOMER_TEMP;

--CREATE SEQUENCE FOR CATEGORY
CREATE SEQUENCE CATEGORY_SEQ
MINVALUE 1
INCREMENT BY 1;

--INSERT IN PRODUCTCATEGORY TABLE
INSERT INTO PRODUCTCATEGORY(PRODUCTCATEGORYID,PRODUCTCATEGORYNAME)
SELECT CATEGORY_SEQ.NEXTVAL,CATEGORYNAME
FROM (
SELECT DISTINCT CATEGORYNAME FROM PRODUCTCATEGORY_TEMP);

--INSERT INTO PRODUCT TABLE
INSERT INTO PRODUCT(PRODUCTID,PRODUCTNUM,MANUFACTURER,FINISH,DESCRIPTION,TITLE,PRODUCTCATEGORYID)
SELECT DISTINCT P.PRODUCTID,P.PRODUCTNUM,P.MANUFACTURER,P.FINISH,P.DESCRIPTION,P.TITLE,C.PRODUCTCATEGORYID
FROM PRODUCT_TEMP P JOIN PRODUCTCATEGORY C
ON UPPER(P.PRODUCTCATEGORYID)=UPPER(C.PRODUCTCATEGORYNAME);

--INSERT INTO ORDERS TABLE
INSERT INTO ORDERS(ORDERID,ORDERDATE,CUSTOMERID,SITEID,STATUSID)
SELECT O.ORDERID,O.ORDERDATE,O.CUSTOMERID,S.SITEID,ST.STATUSID
FROM ORDER_TEMP O JOIN SITE S ON LOWER(S.SITENAME)=LOWER(O.SITENAME)
JOIN STATUS ST ON UPPER(ST.STATUSVALUE)=UPPER(O.STATUSNAME);

--CREATE SEQUENCE FOR ORDER_PRODUCT TABLE
CREATE SEQUENCE ORDER_PRODUCT_SEQ
MINVALUE 1
INCREMENT BY 1;

--INSERT IN ORDER_PROUCT
INSERT INTO ORDER_PRODUCT(UNIQUEID,ORDERID,PRODUCTID,QUANTITY,UNIT_PRICE,TOTALTAX)
SELECT ORDER_PRODUCT_SEQ.NEXTVAL,ORDERID,PRODUCTID,QUANTITY,UNIT_PRICE,TOTALTAX
FROM(
SELECT O.ORDERID ORDERID,T.PRODUCTID PRODUCTID,T.QUANTITY QUANTITY,T.UNIT_PRICE UNIT_PRICE,T.TOTALTAX TOTALTAX
FROM ORDER_PRODUCT_TEMP T JOIN ORDER_TEMP O ON O.ORDERGRPID=T.CARTID
WHERE T.PRODUCTID IS not NULL );

--CREATE SEQUENCE FOR SHIPPINGADDRESS
CREATE SEQUENCE SHIPPING_SEQ
MINVALUE 1
INCREMENT BY 1;

--INSERT INTO SHIPPINGADDRESS FOR USA
INSERT INTO SHIPPINGADDRESS(SHIPPINGID,ADDRESS,CITY,STATE,ZIPCODE,COUNTRY,CUSTOMERID)
SELECT SHIPPING_SEQ.NEXTVAL,ADDRESS,CITY,STATE,ZIPCODE,'USA',CUSTOMERID
FROM(
SELECT ADDRESS,CITY,STATE,ZIPCODE,CUSTOMERID
FROM SHIPPINGADDRESS_TEMP_USA
);

--INSERT INTO SHIPPINGADDRESS FOR CANADA
INSERT INTO SHIPPINGADDRESS(SHIPPINGID,ADDRESS,CITY,STATE,ZIPCODE,COUNTRY,CUSTOMERID)
SELECT SHIPPING_SEQ.NEXTVAL,ADDRESS,CITY,STATE,ZIPCODE,'Canada',CUSTOMERID
FROM(
SELECT ADDRESS,CITY,STATE,ZIPCODE,CUSTOMERID
FROM SHIPPINGADDRESS_TEMP_CANADA
);

--INSERT INTO PRODUCT
INSERT INTO PRODUCT(PRODUCTID)
select distinct productid from po_item_temp where productid not in(select productid from product_temp)

--INSERT INTO PURCHASEORDER
INSERT INTO PURCHASEORDER(PURCHASEORDERID,PURCHASEDATE,ORDERID,STATUSID,VENDORID)
SELECT P.PURCHASEORDERID,P.PURCHASEDATE,P.ORDERID
,S.STATUSID
,V.VENDORID
FROM PURCHASEORDER_TEMP P JOIN STATUS S ON LOWER(P.STATUS)=LOWER(S.STATUSVALUE)
JOIN VENDOR V ON V.VENDORNAME=P.VENDOR;

--CREATE SEQUENCE FOR POITEM
CREATE SEQUENCE POITEM_SEQ1
MINVALUE 1
INCREMENT BY 1;

--INSERT INTO PO_ITEM
INSERT INTO PO_ITEM(PO_ITEM_ID,PRODUCTID,UNITCOST,PURCHASEORDERID,QUANTITY)
SELECT POITEM_SEQ1.NEXTVAL,PRODUCTID,UNITCOST,PURCHASEORDERID,QUANTITY
FROM (
SELECT PRODUCTID,UNITCOST,PURCHASEORDERID,QUANTITY FROM PO_ITEM_TEMP);

--CREATE SEQUENCE FOR PAYEMENT
CREATE SEQUENCE PAY_SEQ
MINVALUE 1
INCREMENT BY 1;

--INSERT INTO PAYMENTTYPE
INSERT INTO PAYMENTTYPE(PAYMENTTYPEID,ADDRESS,CITY,STATE,ZIPCODE,COUNTRY,CUSTOMERID)
SELECT PAY_SEQ.NEXTVAL,ADDRESS,CITY,STATE,ZIPCODE,'CANADA',CUSTOMERID
FROM (
SELECT ADDRESS,CITY,STATE,ZIPCODE,CUSTOMERID FROM PAYMENTTYPE_TEMP);


INSERT INTO PAYMENTTYPE(PAYMENTTYPEID,ADDRESS,CITY,STATE,ZIPCODE,COUNTRY,CUSTOMERID)
SELECT PAY_SEQ.NEXTVAL,ADDRESS,CITY,STATE,ZIPCODE,'USA',CUSTOMERID
FROM (
SELECT ADDRESS,CITY,STATE,ZIPCODE,CUSTOMERID FROM PAYMENTTYPE_TEMP_USA);

--UPDATE ORDERS TABLE WITH  SHIPPINGADDRESS
UPDATE ORDERS O
SET O.SHIPPINGID =
(SELECT   MAX(S.SHIPPINGID) FROM SHIPPINGADDRESS S WHERE S.CUSTOMERID=O.CUSTOMERID)

--UPDATE ORDERS TABLE WITH  PAYMENTTYPE
UPDATE ORDERS O
SET O.PAYMENTTYPEID =
(SELECT   MAX(P.PAYMENTTYPEID) FROM PAYMENTTYPE P WHERE O.CUSTOMERID=P.CUSTOMERID)






